### ISSUE TITLE
Create Spawn Setting Command and Spawn Command

### ISSUE THREAD

**Issue by dpvb** [dpvb/outlast#5]

**Comment by ms5984** [comment]
DB? or nah

**Comment by dpvb** [comment]
This should go in location DB. Location should be named "spawn".

**Comment by dpvb** [comment]
Implemented setspawn, but temporarily implemented spawn command.

Spawn command still needs to use the ChannelingTeleport @ms5984

**Comment by dpvb** [comment]
Implemented.
